//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konditer_FigmaProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dolznost
    {
        public Dolznost()
        {
            this.Stuff = new HashSet<Stuff>();
        }
    
        public int idDolznost { get; set; }
        public string nameDolznost { get; set; }
    
        public virtual ICollection<Stuff> Stuff { get; set; }
    }
}
