//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konditer_FigmaProject.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CondIzd_SamarinREntities : DbContext
    {
        public CondIzd_SamarinREntities()
            : base("name=CondIzd_SamarinREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Account { get; set; }
        public DbSet<OptSalers> OptSalers { get; set; }
        public DbSet<Products> Products { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TypeOptSalers> TypeOptSalers { get; set; }
        public DbSet<Units> Units { get; set; }
        public DbSet<ViewPack> ViewPack { get; set; }
        public DbSet<Stuff> Stuff { get; set; }
    }
}
