//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konditer_FigmaProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptSalers
    {
        public OptSalers()
        {
            this.Account = new HashSet<Account>();
        }
    
        public int IdOptSalers { get; set; }
        public string NameOptSalers { get; set; }
        public int TypeOptSalers { get; set; }
    
        public virtual ICollection<Account> Account { get; set; }
        public virtual TypeOptSalers TypeOptSalers1 { get; set; }
    }
}
