//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konditer_FigmaProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOptSalers
    {
        public TypeOptSalers()
        {
            this.OptSalers = new HashSet<OptSalers>();
        }
    
        public int IdType { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<OptSalers> OptSalers { get; set; }
    }
}
